name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

env:
  PROTOC_VERSION: '25.0'
  PROTOC_GENDOC_VERSION: '1.5.1'
  PROTOC_GO_VERSION: '1.31.0'

jobs:
  generate-all:
    name: "Regenerate Go bindings and proto documentation"
    runs-on: ubuntu-latest
    steps:
      - name: "Install Protoc Binary"
        uses: supplypike/setup-bin@v3
        with:
          uri: "https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/protoc-${{ env.PROTOC_VERSION }}-linux-x86_64.zip"
          name: 'protoc'
          subPath: 'bin'
          version: ${{ env.PROTOC_VERSION }}
      - name: "Install ProtocGenDoc"
        uses: supplypike/setup-bin@v3
        with:
          uri: "https://github.com/pseudomuto/protoc-gen-doc/releases/download/v${{ env.PROTOC_GENDOC_VERSION }}/protoc-gen-doc_${{ env.PROTOC_GENDOC_VERSION }}_linux_amd64.tar.gz"
          name: 'protoc-gen-doc'
          version: ${{ env.PROTOC_GENDOC_VERSION }}
      - name: "Install Protoc Go Binary"
        uses: supplypike/setup-bin@v3
        with:
          uri: "https://github.com/protocolbuffers/protobuf-go/releases/download/v${{ env.PROTOC_GO_VERSION }}/protoc-gen-go.v${{ env.PROTOC_GO_VERSION }}.linux.amd64.tar.gz"
          name: 'protoc-gen-go'
          version: ${{ env.PROTOC_GO_VERSION }}

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Run make all
        run: make all

      - name: Commit changes
        run: |
          git pull origin ${{ github.head_ref }}
          git status
          git config --global user.name github-actions
          git config --global user.email "github-actions@github.com"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: regenerate Go bindings and docs"
            git push origin ${{ github.head_ref }}
          fi
